/*
 * board_power.c - STM32L0 HAL implementation (STM32CubeL0).
 *
 * NOT YET TESTED ON HARDWARE and not compiled against the real HAL in the
 * design environment. Check against RM0377 (STM32L0x1 reference manual):
 *   - WKUP1 edge polarity / behaviour when PA0 is already high at Standby entry.
 *   - ULP + fast wake-up settings for your clock configuration.
 */
#include "board_power.h"
#include "stm32l0xx_hal.h"

extern void SystemClock_Config(void);      /* generated by STM32CubeMX */

#define BTN_PORT   GPIOA
#define BTN_PIN    GPIO_PIN_0
#define HOLD_PIN   GPIO_PIN_1
#define INT_PIN    GPIO_PIN_2
#define VLOW_PIN   GPIO_PIN_3
#define LED_PIN    GPIO_PIN_4
#define VSNS_PIN   GPIO_PIN_5

static ADC_HandleTypeDef hadc;

boot_reason_t board_power_init(void)
{
    GPIO_InitTypeDef g = {0};
    boot_reason_t why = BOOT_POWER_ON;

    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_PWR_CLK_ENABLE();

    /* Keep the latch ON first: PS_HOLD is also pulled up in hardware. */
    HAL_GPIO_WritePin(GPIOA, HOLD_PIN, GPIO_PIN_SET);
    g.Pin = HOLD_PIN; g.Mode = GPIO_MODE_OUTPUT_PP; g.Pull = GPIO_NOPULL; g.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &g);

    if (__HAL_PWR_GET_FLAG(PWR_FLAG_SB)) {
        why = BOOT_FROM_STANDBY;
        __HAL_PWR_CLEAR_FLAG(PWR_FLAG_SB);
    }
    __HAL_PWR_CLEAR_FLAG(PWR_FLAG_WU);
    HAL_PWR_DisableWakeUpPin(PWR_WAKEUP_PIN1);

    /* Button: external pull-up, interrupt on both edges for gesture timing. */
    g.Pin = BTN_PIN; g.Mode = GPIO_MODE_IT_RISING_FALLING; g.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(BTN_PORT, &g);
    HAL_NVIC_SetPriority(EXTI0_1_IRQn, 3, 0);
    HAL_NVIC_EnableIRQ(EXTI0_1_IRQn);

    g.Pin = INT_PIN | VLOW_PIN; g.Mode = GPIO_MODE_INPUT; g.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &g);

    HAL_GPIO_WritePin(GPIOA, LED_PIN, GPIO_PIN_RESET);
    g.Pin = LED_PIN; g.Mode = GPIO_MODE_OUTPUT_PP;
    HAL_GPIO_Init(GPIOA, &g);

    g.Pin = VSNS_PIN; g.Mode = GPIO_MODE_ANALOG;
    HAL_GPIO_Init(GPIOA, &g);

    return why;
}

bool board_button_pressed(void) { return HAL_GPIO_ReadPin(BTN_PORT, BTN_PIN) == GPIO_PIN_RESET; }
bool board_battery_low(void)    { return HAL_GPIO_ReadPin(GPIOA, VLOW_PIN) == GPIO_PIN_RESET; }
void board_led(bool on)         { HAL_GPIO_WritePin(GPIOA, LED_PIN, on ? GPIO_PIN_SET : GPIO_PIN_RESET); }

/*
 * VBAT/2 is taken from the STM6601 EN output (=VCC of the STM6601 when ON), so
 * this reads roughly the battery voltage. 4.7M source impedance: C12 (100 nF)
 * holds the node; use the longest sample time. Reference = VDD (3.3 V LDO), so
 * the reading is only valid while VBAT > ~3.4 V (LDO in regulation).
 */
uint32_t board_vbat_mv(void)
{
    ADC_ChannelConfTypeDef ch = {0};
    uint32_t raw;

    __HAL_RCC_ADC1_CLK_ENABLE();
    hadc.Instance = ADC1;
    hadc.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc.Init.Resolution = ADC_RESOLUTION_12B;
    hadc.Init.DataAlign = ADC_DATAALIGN_RIGHT;
    hadc.Init.ScanConvMode = ADC_SCAN_DIRECTION_FORWARD;
    hadc.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
    hadc.Init.SamplingTime = ADC_SAMPLETIME_160CYCLES_5;
    hadc.Init.ContinuousConvMode = DISABLE;
    hadc.Init.ExternalTrigConv = ADC_SOFTWARE_START;
    hadc.Init.LowPowerAutoPowerOff = ENABLE;
    HAL_ADC_Init(&hadc);
    HAL_ADCEx_Calibration_Start(&hadc, ADC_SINGLE_ENDED);

    ch.Channel = ADC_CHANNEL_5; ch.Rank = ADC_RANK_CHANNEL_NUMBER;
    HAL_ADC_ConfigChannel(&hadc, &ch);
    HAL_ADC_Start(&hadc);
    HAL_ADC_PollForConversion(&hadc, 10);
    raw = HAL_ADC_GetValue(&hadc);
    HAL_ADC_Stop(&hadc);
    HAL_ADC_DeInit(&hadc);
    __HAL_RCC_ADC1_CLK_DISABLE();

    return (raw * 3300u * 2u) / 4095u;
}

void board_sleep(void)
{
    board_led(false);
    HAL_SuspendTick();
    HAL_PWREx_EnableUltraLowPower();       /* VREFINT off in Stop            */
    HAL_PWREx_EnableFastWakeUp();          /* don't wait for VREFINT on wake */
    HAL_PWR_EnterSTOPMode(PWR_LOWPOWERREGULATOR_ON, PWR_STOPENTRY_WFI);
    /* --- wakes here on the button edge (EXTI0) or any enabled EXTI/RTC --- */
    SystemClock_Config();                  /* Stop leaves the MCU on MSI     */
    HAL_ResumeTick();
}

void board_deep_sleep(void)
{
    board_led(false);
    while (board_button_pressed()) { }     /* enter with the button released */
    HAL_Delay(30);
    HAL_PWR_DisableWakeUpPin(PWR_WAKEUP_PIN1);
    __HAL_PWR_CLEAR_FLAG(PWR_FLAG_WU);
    HAL_PWR_EnableWakeUpPin(PWR_WAKEUP_PIN1);
    HAL_PWREx_EnableUltraLowPower();
    HAL_PWR_EnterSTANDBYMode();
    for (;;) { }                           /* wake-up = reset */
}

void board_power_off(void)
{
    board_led(false);
    while (board_button_pressed()) { }     /* let go first, so the release isn't */
    HAL_Delay(30);                         /* seen as a new power-on press       */
    HAL_GPIO_WritePin(GPIOA, HOLD_PIN, GPIO_PIN_RESET);
    for (;;) { }                           /* 3.3 V disappears within ms */
}
