// generated by card/build/build.mjs — do not edit
const CACHE='karthick-card-76231b7a67';
const ASSETS=["./","index.html","print.html","contact.vcf","og.png","portrait.webp","details.html","Karthick-A-details.pdf","Karthick-A-resume.pdf","vendor/qrcode.js","fonts/plexmono-400-latin.woff2","fonts/plexmono-500-latin.woff2","fonts/unbounded-latin-var.woff2"];
self.addEventListener('install',e=>{
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).catch(()=>{}));
});
self.addEventListener('activate',e=>{
  e.waitUntil(caches.keys().then(ks=>Promise.all(
    ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));
});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(res=>{
    const copy=res.clone();
    if(res.ok&&new URL(e.request.url).origin===location.origin)
      caches.open(CACHE).then(c=>c.put(e.request,copy));
    return res;
  }).catch(()=>caches.match('./'))));
});
